### ISSUE TITLE
这个版本用在生产环境稳定吗

### ISSUE THREAD

**Issue by lb151** [aliyun/alibabacloud-oss-go-sdk-v2#15]
V2版本稳定了没，可以用在生产环境吗

**Comment by shuqingzai** [comment]
同问，看到版本已经发布 [v1.0.0](https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/releases/tag/v1.0.0) 
这是否意味着 V2 版可以用于生产？？？

**Comment by huiguangjun** [comment]
该版本基本稳定了，使用过程中，如果遇到问题，请反馈给我们。
