### ISSUE TITLE
如何获取生成URL

### ISSUE THREAD

**Issue by zyfjfj** [aliyun/alibabacloud-oss-go-sdk-v2#18]
之前的api中有SignURL(),v2如何获取？

**Comment by huiguangjun** [comment]
请参考该接口使用说明 https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/DEVGUIDE-CN.md#%E9%A2%84%E7%AD%BE%E5%90%8D%E6%8E%A5%E5%8F%A3

**Comment by huiguangjun** [comment]
从v1迁移到 v2，可以参考 [迁移指南](https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/DEVGUIDE-CN.md#%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97)，
