### ISSUE TITLE
Bucket Policy之类的方法在V2中没有支持吗

### ISSUE THREAD

**Issue by gmars** [aliyun/alibabacloud-oss-go-sdk-v2#23]
Bucket Policy之类的方法在V2中没有支持吗

**Comment by huiguangjun** [comment]
1. 其它基础接口 后续会逐步添加

2. v2版本提供了 通用接口client.InvokeOperation，可以通过该接口 访问  oss 已支持的 restful api

以bucket policy 为例, 可以参考  测试用例  [TestInvokeOperation_BucketPolicy](https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/oss/client_integration_test.go#L429) 写法.
