### ISSUE TITLE
专有云容量问题

### ISSUE THREAD

**Issue by lin-chong** [aliyun/alibabacloud-oss-go-sdk-v2#68]
请教一下, 请求专有云创建bucket时, 如何设置容量, 我看PutBucketRequest没有容量相关的参数

**Comment by huiguangjun** [comment]
1. 可以先咨询专有云的支持同学，是否有这类接口
2. 如果有这个接口，可以通过 泛化接口 进行设置。接口的 的定义参考[ func (c *Client) InvokeOperation(ctx context.Context, input *OperationInput, optFns ...func(*Options)) (*OperationOutput, error) ](https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/oss/api_op_common.go)
3. 该接口的使用方法参考  示例 [func TestInvokeOperation_BucketPolicy(t *testing.T) ](https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/oss/client_integration_test.go#L505)
填写相应的 header，query ，body 参数。 v1签名涉及到 签名子资源的概念，还需要通过 OperationInput.OpMetadata.Set(signer.SubResource, []string{"xxx"})  方式设置。
