### ISSUE TITLE
有没有要做PostObjectRequest的准备?

### ISSUE THREAD

**Issue by huhu415** [aliyun/alibabacloud-oss-go-sdk-v2#74]
比如这样:
```
	client := oss.NewClient(cfg)

	request := &oss.PostObjectRequest{
		Bucket: oss.Ptr("phtoto"),
		Key:    oss.Ptr("123.txt"),
	}
	expiration := time.Now().Add(100 * time.Minute)
	result, err := client.Presign(context.TODO(), request, oss.PresignExpiration(expiration))
	if err != nil {
		fmt.Printf("Presign Error:%v\n", err)
		return
	}
```
说一下为什么要做这个, 我有一个需求是用户上传完文件后, 我可以知道是哪个用户上传的文件, 并且中间是安全, 不能篡改的.

用户来请求golang后端, golang后端可以知道这个用户是谁, 然后通过后把权限交给这个用户了, 用户通过前端上传了图片后, 把我是谁这个信息通过var自定参数给到oss, 然后oss有回调给到golang后端, 然后golang知道了有人上传了东西, 知道了是谁. 

> 但这样有一个问题就是: 前端可以随便设置var, 也就是我是谁, 这样不安全. 改进成:

用户来请求golang后端, golang后端可以知道这个用户是谁, 然后把用户信息+权限交给这个用户, 用了policy把信息锁上了, 用户上传了图片后, 把我是谁这个信息通过var自定参数给到oss, oss, 会根据这个用户信息+权限, 验证一个对不对, 也就是通过那个eq参数, 还有policy, 然后oss有回调给到golang后端, 然后golang知道了有人上传了东西, 知道了是谁.

最终问题有两个:
1. 除了我这种方法还有其他方案么?
2. 如果没有了的话, PostObjectRequest感觉还有点必要.

**Comment by huiguangjun** [comment]
oss 提供了三种签名 模式 ：header 签名， query 签名 和  表单 签名。
1）对于 header 签名，后端需要把临时token返回给 用户，用户上传数据，可以通过 token限制到指定的对象资源。
2）对于query签名，即预签名，CallbackVar 这个参数 参与到 签名里，即设置后 就不能修改，不存在用户随便设置的情况。
3）表单签名。签名的签名 和 表单使用 一般是分开的。所以 sdk 不直接提供 PostObject 接口，而是 通过示例的方式  介绍 如何生成 policy 和签名。
具体参考  https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/sample/post_object.go
